<?xml version="1.0"?>
<package format="2">
  <name>behavior_tree_ros</name>
  <version>0.0.1</version>
  <description>ROS Behavior Tree package</description>

  <maintainer email="apaegue@upo.es">Álvaro Páez</maintainer>

  <license>TODO</license>

  <buildtool_depend>catkin</buildtool_depend>
  
  <build_depend>roscpp</build_depend>
  <build_depend>behavior_tree_core</build_depend>
  <build_depend>ros_type_introspection</build_depend>
  <build_depend>topic_tools</build_depend>
  <build_depend>behavior_tree_core</build_depend>
  <build_depend>message_generation</build_depend>

  <build_export_depend>roscpp</build_export_depend>
  <build_export_depend>behavior_tree_core</build_export_depend>
  <build_export_depend>ros_type_introspection</build_export_depend>
  <build_export_depend>topic_tools</build_export_depend>
  <build_export_depend>behavior_tree_core</build_export_depend>

  <exec_depend>message_runtime</exec_depend>

  <export>
  </export>
</package>
