<?xml version="1.0"?>
<package format="2">
  <name>behavior_tree_ros</name>

  <version>0.7.0</version>

  <description>ROS Behavior Tree package</description>

  <maintainer email="jponchu@upo.es">Javier Ponce</maintainer>
  <author>Álvaro Páez</author>

  <license>TODO</license>

  <buildtool_depend>catkin</buildtool_depend>
  
  <build_depend>roscpp</build_depend>
  <build_depend>behavior_tree_cpp</build_depend>
  <build_depend version_gte="2.0.4">ros_type_introspection</build_depend>
  <build_depend>topic_tools</build_depend>
  <build_depend>message_generation</build_depend>
  <build_depend>cmake_modules</build_depend>
  <build_depend>actionlib</build_depend>
  <build_depend>tf</build_depend>
  <build_depend>yaml-cpp</build_depend>
  <build_depend>angles</build_depend>

  <build_export_depend>roscpp</build_export_depend>
  <build_export_depend>behavior_tree_cpp</build_export_depend>
  <build_export_depend version_gte="2.0.4">ros_type_introspection</build_export_depend>
  <build_export_depend>topic_tools</build_export_depend>
  <build_export_depend>cmake_modules</build_export_depend>
  <build_export_depend>actionlib</build_export_depend>
  <build_export_depend>tf</build_export_depend>
  <build_export_depend>angles</build_export_depend>

  <exec_depend>message_runtime</exec_depend>
  <exec_depend>behavior_tree_cpp</exec_depend>
  <exec_depend version_gte="2.0.4">ros_type_introspection</exec_depend>
  <exec_depend>actionlib</exec_depend>
  <exec_depend>tf</exec_depend>
  <exec_depend>yaml-cpp</exec_depend>
  <exec_depend>angles</exec_depend>

  <export>
      <behavior_tree_ros plugin="${prefix}/plugin_description.xml" />
      <behavior_tree_ros palette="${prefix}/palette_description.xml" />
  </export>
</package>
