name: integration-pipeline-ros2

on: 
  push:
    branches: [ "jazzy" ]
  pull_request:
    branches: [ "jazzy" ]

  workflow_dispatch:
    inputs:
      example_input:
        description: 'An example input'
        required: false
        default: 'default value'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: osrf/ros:jazzy-desktop-full
      options: --user root  # Needed for installing additional dependencies with apt
    steps:      
      - name: Fix ROS 2 apt keys
        run: |
          rm /etc/apt/sources.list.d/ros2-latest.list && rm /usr/share/keyrings/ros2-latest-archive-keyring.gpg
          apt-get update && apt-get install -y ca-certificates curl
          export ROS_APT_SOURCE_VERSION=$(curl -s https://api.github.com/repos/ros-infrastructure/ros-apt-source/releases/latest | grep -F "tag_name" | awk -F\" '{print $4}') ; curl -L -s -o /tmp/ros2-apt-source.deb "https://github.com/ros-infrastructure/ros-apt-source/releases/download/${ROS_APT_SOURCE_VERSION}/ros2-apt-source_${ROS_APT_SOURCE_VERSION}.$(. /etc/os-release && echo $VERSION_CODENAME)_all.deb"
          apt-get update
          apt-get install /tmp/ros2-apt-source.deb 
          rm -f /tmp/ros2-apt-source.deb

          curl -L -s -o /tmp/ros2-apt-source.deb https://github.com/ros-infrastructure/ros-apt-source/releases/download/1.1.0/ros2-apt-source_1.1.0.noble_all.deb 

          echo "35441f3092fd05773a3c397fab38661bec466584c7a1f1c05366579997cb5fe7 /tmp/ros2-apt-source.deb" | sha256sum --strict --check
          apt-get update 
          apt-get install /tmp/ros2-apt-source.deb 

          rm -f /tmp/ros2-apt-source.deb
          rm -rf /var/lib/apt/lists/*

      - name: download dependencies
        run: |
          ls        
          mkdir -p ~/ros2_ws/src
          cd ~/ros2_ws/src
          pwd
          git clone https://github.com/eurecat/rosx_introspection.git -b master                    
          git clone https://x-access-token:${{ secrets.GH_PAT }}@github.com/Eurecat/behaviortree_eut_plugins.git -b jazzy
          git clone https://github.com/BehaviorTree/BehaviorTree.CPP.git -b 4.6.2
          ls
      - name: setup the ws
        shell: bash
        run: |
          pwd
          echo "source /opt/ros/jazzy/setup.bash" >> ~/.bashrc
          source ~/.bashrc          
          cd ~/ros2_ws
          ls
          colcon build
          source install/setup.bash
          ls          
          pwd
      - name: Build the workspace
        shell: bash
        run: |    
          cd ~/ros2_ws/src
          git clone https://github.com/${{ github.repository }}.git
          cd ~/ros2_ws
          source ~/ros2_ws/install/setup.bash                  
          colcon build
          
